name: Flask App CI/CD

on:
  push:
    branches:
      - main
      - backend
      - frontend
      - devops

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd main
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          cd main
          pytest -v --maxfail=1 --disable-warnings

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/flask_lab_project:latest ./main

      - name: Push Docker image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/flask_lab_project:latest
